version: 0.2

env:
  variables:
    PACKAGE: "https://github.com/eL0ck/anzi-demo.git"
    ARTIFACT_BUCKET: "teal-ml-lambda-bucket"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade awscli
  build:
    commands:
      - "aws cloudformation package \
          --template-file template.yaml \
          --s3-bucket ${ARTIFACT_BUCKET} \
          --s3-prefix anzi-demo  \
          --output-template /tmp/packaged.yaml"
      - "aws cloudformation deploy \
          --capabilities CAPABILITY_IAM \
          --template-file /tmp/packaged.yaml \
          --stack-name anzi-demo-stack"
artifacts:
  files:
    - /tmp/packaged.yaml
  discard-paths: yes
